# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and upload the app to Firebase App Distribution"
  lane :distribute_to_firebase do |options|
    setup_ci
    match(type: "adhoc", readonly: true)

    build_app(
      scheme: "Palette",
      export_method: "ad-hoc",
    )

    firebase_app_distribution(
      app: options[:firebase_app_id],
      groups: "testers",
      release_notes_file: options[:release_notes_file],
    )
  end
end
