[versions]
androidx-activity-compose = "1.13.0"
androidx-core-splashscreen = "1.2.0"
androidx-lifecycle = "2.11.0"
androidx-navigation3 = "1.1.7"
androidx-test-ext-junit = "1.3.0"
coil = "3.6.2"
compose-multiplatform-material3 = "1.11.0-alpha07"
compose-multiplatform-material-icons-extended = "1.7.3"
embarrasdf-gradle-plugins = "0.0.129"
junit = "4.13.2"
kotlinx-collections-immutable = "0.5.2"
kotlinx-coroutines = "1.11.0"
kotlinx-datetime = "0.8.0-0.6.x-compat"
kotlinx-serialization-json = "1.11.0"
ktor = "3.5.2"
navigation3 = "1.1.2"
navigation3-browser = "1.1.0"
navigationevent = "1.1.0"
paparazzi = "2.0.0-SNAPSHOT"
profileinstaller = "1.4.1"
test-parameter-injector = "1.22"
uiautomator = "2.4.0"
trace = "0.0.17"
uievent = "0.0.19"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity-compose" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx-core-splashscreen" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileinstaller" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-network-ktor3 = { group = "io.coil-kt.coil3", name = "coil-network-ktor3", version.ref = "coil" }
compose-material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "compose-multiplatform-material3" }
compose-material-icons-extended = { group = "org.jetbrains.compose.material", name = "material-icons-extended", version.ref = "compose-multiplatform-material-icons-extended" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-android = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor" }
ktor-client-darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
ktor-client-java = { group = "io.ktor", name = "ktor-client-java", version.ref = "ktor" }
navigation3-browser = { module = "com.github.terrakok:navigation3-browser", version.ref = "navigation3-browser" }
navigation3-runtime = { group = "androidx.navigation3", name = "navigation3-runtime", version.ref = "androidx-navigation3" }
navigation3-ui = { group = "org.jetbrains.androidx.navigation3", name = "navigation3-ui", version.ref = "navigation3" }
navigationevent = { group = "org.jetbrains.androidx.navigationevent", name = "navigationevent-compose", version.ref = "navigationevent" }
paparazzi = { group = "app.cash.paparazzi", name = "paparazzi", version.ref = "paparazzi" }
test-parameter-injector = { group = "com.google.testparameterinjector", name = "test-parameter-injector", version.ref = "test-parameter-injector" }
trace = { group = "com.embarrasdf.trace", name = "trace", version.ref = "trace" }
uievent = { group = "com.embarrasdf.uievent", name = "uievent", version.ref = "uievent" }

[plugins]
embarrasdf-android-application = { id = "com.embarrasdf.gradle.plugin.android.application", version.ref = "embarrasdf-gradle-plugins" }
embarrasdf-android-application-compose = { id = "com.embarrasdf.gradle.plugin.android.application.compose", version.ref = "embarrasdf-gradle-plugins" }
embarrasdf-android-baselineprofile-consumer-app = { id = "com.embarrasdf.gradle.plugin.android.baselineprofile.consumer.app", version.ref = "embarrasdf-gradle-plugins" }
embarrasdf-android-baselineprofile-consumer-library = { id = "com.embarrasdf.gradle.plugin.android.baselineprofile.consumer.library", version.ref = "embarrasdf-gradle-plugins" }
embarrasdf-android-baselineprofile-generator = { id = "com.embarrasdf.gradle.plugin.android.baselineprofile.generator", version.ref = "embarrasdf-gradle-plugins" }
embarrasdf-android-benchmark = { id = "com.embarrasdf.gradle.plugin.android.benchmark", version.ref = "embarrasdf-gradle-plugins" }
embarrasdf-android-compose-test = { id = "com.embarrasdf.gradle.plugin.android.compose.test", version.ref = "embarrasdf-gradle-plugins" }
embarrasdf-android-instrumented-test = { id = "com.embarrasdf.gradle.plugin.android.instrumented.test", version.ref = "embarrasdf-gradle-plugins" }
embarrasdf-android-library = { id = "com.embarrasdf.gradle.plugin.android.library", version.ref = "embarrasdf-gradle-plugins" }
embarrasdf-android-library-compose = { id = "com.embarrasdf.gradle.plugin.android.library.compose", version.ref = "embarrasdf-gradle-plugins" }
embarrasdf-android-test = { id = "com.embarrasdf.gradle.plugin.android.test", version.ref = "embarrasdf-gradle-plugins" }
embarrasdf-compose-multiplatform = { id = "com.embarrasdf.gradle.plugin.compose.multiplatform", version.ref = "embarrasdf-gradle-plugins" }
embarrasdf-desktop-application = { id = "com.embarrasdf.gradle.plugin.desktop.application", version.ref = "embarrasdf-gradle-plugins" }
embarrasdf-github-release = { id = "com.embarrasdf.gradle.plugin.github.release", version.ref = "embarrasdf-gradle-plugins" }
embarrasdf-kotlin-multiplatform-library = { id = "com.embarrasdf.gradle.plugin.kotlin.multiplatform.library", version.ref = "embarrasdf-gradle-plugins" }
embarrasdf-kotlin-serialization = { id = "com.embarrasdf.gradle.plugin.kotlin.serialization", version.ref = "embarrasdf-gradle-plugins" }
embarrasdf-maven-publish = { id = "com.embarrasdf.gradle.plugin.maven.publish", version.ref = "embarrasdf-gradle-plugins" }
embarrasdf-web-application = { id = "com.embarrasdf.gradle.plugin.web.application", version.ref = "embarrasdf-gradle-plugins" }
paparazzi = { id = "app.cash.paparazzi", version.ref = "paparazzi" }

[bundles]
