# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build and upload the app to Firebase App Distribution"
  lane :distribute_to_firebase do |options|
    gradle(
      task: "assembleRelease",
      project_dir: "../../",
    )

    firebase_app_distribution(
      app: options[:firebase_app_id],
      groups: "testers",
      release_notes_file: options[:release_notes_file],
      android_artifact_path: "build/outputs/apk/release/androidApp-release.apk",
#       android_artifact_path: "build/outputs/bundle/release/androidApp-release.aab",
    )
  end
end
